- name: midterm exam
  hosts: elasticsearch
  tags: elasticsearch,ubuntu
  tasks:
    - name: Include variables
      include_vars:
        file: config.yml

    - name: Install Elasticsearch dependency (ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package: openjdk-8-jdk
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Nginx (ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package: nginx
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stopping Apache2 (ubuntu)
      service:
        name: apache2
        state: stopped
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install apt-transport-https
      include_role:
        name: installpkgubuntu
      vars:
        package: apt-transport-https
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Configure Elasticsearch (Ubuntu)
      include_role:
        name: Elasubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      
- name: elasticsearch
  hosts: elasticsearch
  tags: elasticsearch,centos
  tasks:
    - name: Include variables
      include_vars:
        file: config.yml

    - name: Install Java [Elastic search dependency] (CentOS)
      include_role:
        name: installpkgcentos
      vars:
        package: java-1.8.0-openjdk
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Configuring Elastic Search (CentOS)
      include_role:
        name: Elascentos
      when: ansible_facts['distribution'] == 'CentOS'

- name: Install and Configure Kibana
  hosts: kibana
  tags: kibana,ubuntu
  tasks:
    - name: Include vars
      include_vars:
        file: config.yml

    - name: Install Kibana (Ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package: kibana
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Configure Kibana (Ubuntu)
      include_role:
        name: Kiubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      
- name: Install and Configure Kibana
  hosts: kibana
  tags: kibana,centos
  tasks:
    - name: Include vars
      include_vars:
        file: config.yml

    - name: Install Kibana (CentOS)
      include_role:
        name: installpkgcentos
      vars:
        package: kibana
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Configure Kibana (CentOS)
      include_role:
        name: Kicentos
      when: ansible_facts['distribution'] == 'CentOS'


- name: Install and Configure Logstash
  hosts: logstash
  tags: logstash,ubuntu
  tasks:
    - name: Include vars
      include_vars:
        file: config.yml

    - name: Install Logstash (Ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package: logstash
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Configure Logstash (Ubuntu)
      include_role:
        name: Logubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install and Configure Logstash
  hosts: logstash
  tags: logstash,centos
  tasks:
    - name: Include vars
      include_vars:
        file: config.yml

    - name: Install logstash (CentOS)
      include_role:
        name: installpkgcentos
      vars:
        package: logstash
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Configure logstash (CentOS)
      include_role:
        name: Logcentos
      when: ansible_facts['distribution'] == 'CentOS'

- name: Install and Configure Nagios in Ubuntu Host
  hosts: nagios
  tags: nagios,ubuntu
  tasks:
    - name: Include global variable
      include_vars:
        file: config.yaml
    
    - name: Stop Nginx
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Install Nagios dependencies (Ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package:
          - autoconf
          - gcc
          - libc6
          - make
          - wget
          - libssl-dev
          - gawk
          - dc
          - build-essential
          - snmp
          - libnet-snmp-perl
          - gettext
          - unzip
          - apache2
          - php
          - libapache2-mod-php7.4
          - libgd-dev
          - python3
          - python3-pip
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install nagios and configure (Ubuntu)
      include_role:
        name: Nagiosubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stopping UFW (Ubuntu)
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install and Configure Grafana
  tags: grafana,ubuntu,centos
  hosts: grafana
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Disabling Apache2
      service:
        name: apache2
        state: stopped

    - name: Enabling Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install and configure Grafana (Ubuntu)
      include_role:
        name: Grafanaubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install and configure Grafana (CentOS)
      include_role:
        name: Grafanacentos
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Stopping UFW (Ubuntu)
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stopping Firewalld (CentOS)
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'

- name: Install and Configure InfluxDB
  tags: influxdb,ubuntu,centos
  hosts: influxdb
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Install and Configure InfluxDB (Ubuntu)
      include_role:
        name: influxdbubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install and Configure InfluxDB (CentOS)
      include_role:
        name: influxdbcentos
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Stopping UFW
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stopping Firewalld
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'

- name: Install and Configure Prometheus
  tags: prom,ubuntu,centos
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Disabling Apache2
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Enabling Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install and Configure Prometheus (Ubuntu)
      include_role:
        name: promubuntu
      vars:
        src: "{{ prometheus_src }}"
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install and Configure Prometheus (CentOS)
      include_role:
        name: promcentos
      vars:
        src: "{{ prometheus_src }}"
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stop UFW (Ubuntu)
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stop Firewalld (CentOS)
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'


- name: Install and Configure Apache2 and HTTPD
  hosts: webserver
  tags: httpd,apache2,ubuntu,centos
  tasks:
    - name: Include config.yaml variables
      include_vars:
        file: config.yaml

    - name: Install Apache in Ubuntu
      include_role:
        name: installpkgubuntu
      vars:
        package:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql

      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install HTTPD in CentOS
      include_role:
        name: installpkgcentos
      vars:
        package:
          - httpd
          - php
          - php-mysqlnd
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Configure Apache2 (Ubuntu)
      include_role:
        name: Apacheubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Configure HTTPD (CentOS)
      include_role:
        name: Httpdcentos
      when: ansible_facts['distribution'] == 'CentOS'

- name: Install and Configure MariaDB
  hosts: mariadb
  tags: mariadb,ubuntu,centos
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yaml

    - name: Install Mariadb (Ubuntu)
      include_role:
        name: installpkgubuntu
      vars:
        package: mariadb-server
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Mariadb (CentOS)
      include_role:
        name: installpkgcentos
      vars:
        package: mariadb-server
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Stop UFW (Ubuntu)
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Stop Firewalld (CentOS)
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Configure MariaDB (Ubuntu)
      include_role:
        name: Mariaubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Configure MariaDB (CentOS)
      include_role:
        name: Mariacentos
      when: ansible_facts['distribution'] == 'CentOS'
